CREATE DATABASE IF NOT EXISTS instaclone;

USE instaclone;

CREATE TABLE IF NOT EXISTS user (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mobile VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  fullname VARCHAR(255),
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  birthday DATE,
  PRIMARY KEY (id)
);
